services:

  postgres:
    container_name: psql-db
    image: postgres
    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: test123
      POSTGRES_USER: kkujufcykdotuw
      POSTGRES_PASSWORD: cdc2c9d17eb7b734c15800406ec787543ba533de94167e6c097b18fb10049d1c
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped

  pgadmin:
    container_name: psql-db-PgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - database
    restart: unless-stopped

networks:
  database:
    driver: bridge

volumes:
  postgres:
  pgadmin: