services:

  postgres:
    container_name: psql-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped

networks:
  database:
    driver: bridge

volumes:
  postgres:
  pgadmin: