name: Heroku Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    run: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Heroku
    uses: AkhileshNS/heroku-deploy@v3.12.12
    with:
      # This will be used for authentication. You can find it in your heroku homepage account settings
      heroku_api_key: ${{secrets.SBHEROKU_API_KEY}}
      # Email that you use with heroku
      heroku_email: ${{secrets.SBHEROKU_EMAIL}}
      # The appname to use for deploying/updating
      heroku_app_name: ${{secrets.SBHEROKU_APP_NAME}}

